# Generated by Django 4.1.1 on 2023-12-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='depot.facture'),
        ),
    ]
