# Generated by Django 4.2 on 2023-12-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_mouvement_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='situation',
            field=models.CharField(blank=True, default='NON', max_length=30, null=True),
        ),
    ]
