# Generated by Django 4.2 on 2023-12-31 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depot', '0003_facture_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_payement', models.CharField(max_length=80, unique=True)),
                ('date_payement', models.DateField()),
                ('mt_facture', models.IntegerField(default=0)),
                ('mt_reglee', models.IntegerField(default=0)),
                ('mt_encaisse', models.IntegerField(default=0)),
                ('mt_restant', models.IntegerField(default=0)),
                ('reliquat', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.facture')),
            ],
        ),
    ]
