# Generated by Django 4.1.1 on 2024-01-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0005_remove_payement_mt_facture_remove_payement_mt_reglee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'GESTION DES CLIENTS'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name_plural': 'GESTION DES FACTURES'},
        ),
        migrations.AlterModelOptions(
            name='modelb',
            options={'verbose_name_plural': 'GESTION DES MODELS'},
        ),
        migrations.AlterModelOptions(
            name='moder',
            options={'verbose_name_plural': 'GESTION DES MODES DE REGLEMENT'},
        ),
        migrations.AlterModelOptions(
            name='payement',
            options={'verbose_name_plural': 'GESTION DES PAYEMENTS'},
        ),
        migrations.AlterModelOptions(
            name='producteur',
            options={'verbose_name_plural': 'GESTION DES PRODUCTEURS'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name_plural': 'GESTION DES PRODUITS'},
        ),
        migrations.AddField(
            model_name='payement',
            name='moder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='depot.moder'),
        ),
        migrations.AddField(
            model_name='payement',
            name='mt_encaisse_jour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payement',
            name='code_payement',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
