# Generated by Django 4.1.1 on 2024-01-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0005_remove_payement_mt_facture_remove_payement_mt_reglee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'GESTION DES CLIENTS'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name_plural': 'GESTION DES FACTURES'},
        ),
        migrations.AlterModelOptions(
            name='modelb',
            options={'verbose_name_plural': 'GESTION DES MODELS'},
        ),
        migrations.AlterModelOptions(
            name='moder',
            options={'verbose_name_plural': 'GESTION DES MODES DE REGLEMENT'},
        ),
        migrations.AlterModelOptions(
            name='payement',
            options={'verbose_name_plural': 'GESTION DES PAYEMENTS'},
        ),
        migrations.AlterModelOptions(
            name='producteur',
            options={'verbose_name_plural': 'GESTION DES PRODUCTEURS'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name_plural': 'GESTION DES PRODUITS'},
        ),
    ]
