# Generated by Django 4.1.1 on 2024-01-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_alter_client_options_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='type_client',
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
