# Generated by Django 4.1.1 on 2024-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0007_remove_facture_type_client_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payement',
            old_name='mt_encaisse_jour',
            new_name='mt_recu',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='rs',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
