# Generated by Django 4.1.1 on 2024-01-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0007_remove_facture_type_client_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='moder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.moder'),
        ),
    ]
