# Generated by Django 4.1.1 on 2024-01-16 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0008_alter_payement_moder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='moder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='depot.moder'),
        ),
    ]
