# Generated by Django 4.1.1 on 2024-01-17 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0009_alter_payement_moder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='moder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='depot.moder'),
        ),
    ]
