# Generated by Django 4.1.1 on 2024-01-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0009_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='table',
            field=models.CharField(max_length=80),
        ),
    ]
