# Generated by Django 4.1.1 on 2024-01-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0010_alter_historique_table'),
        ('depot', '0010_alter_payement_moder'),
    ]

    operations = [
    ]
