# Generated by Django 4.1.1 on 2024-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0010_alter_historique_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rs',
            field=models.CharField(max_length=80),
        ),
    ]
