# Generated by Django 4.1.1 on 2024-01-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0012_alter_client_rs'),
        ('depot', '0012_alter_client_type_alter_historique_action'),
    ]

    operations = [
    ]
